use logos::Logos;

#[derive(Logos, Debug, PartialEq)]
#[logos(skip r"[ \t\n\f]+")] 
#[logos(skip r"//.*")]       
pub enum JutsuToken {
    #[token("let")] Let,
    #[token("def")] Def,     
    #[token("print")] Print,
    #[token("import")] Import,
    #[token("input")] Input,
    #[token("read_text")] ReadText,
    #[token("rag")] Rag, 
    #[token("recv")] Recv,
    #[token("reply")] Reply,
    #[token("if")] If,
    #[token("else")] Else,
    #[token("while")] While, 
    #[token("hextrace")] HexTrace, 
    #[token("true")] True,
    #[token("false")] False,
    #[token("return")] Return, 
    #[token("tensor")] Tensor,
    #[token("grad")] Grad,
    #[token("backward")] Backward,
    #[token("optim")] Optim, 
    #[token("[")] BracketOpen,
    #[token("]")] BracketClose,
    #[regex(r"[a-zA-Z_][a-zA-Z0-9_]*")] Identifier,
    #[regex(r#""(?:[^"\\]|\\.)*""#)] 
    #[regex(r#""""([^"]|"[^"]|""[^"])*""""#)] StringLiteral,
    #[regex(r"[0-9]+(\.[0-9]+)?")] Number,
    
    // MATHEMATICAL & LOGICAL OPERATORS
    #[token("+")] Plus,
    #[token("-")] Minus,
    #[token("*")] Star,
    #[token("/")] Slash,
    #[token("%")] Modulo,
    #[token("!")] Bang,
    #[token("=")] Equal,
    #[token(":")] Colon,
    #[token("==")] EqualEqual,
    #[token("!=")] NotEqual,
    #[token("<")] LessThan,
    #[token(">")] GreaterThan,
    #[token(">=")] GreaterEqual,
    #[token("<=")] LessEqual,
    #[token("&&")] And,
    #[token("||")] Or,
    #[token(".")] Dot,
    #[token("infer")] Infer,
    #[token("mcp_server")] McpServer,
    #[token("expose")] ExposeTool,
    #[token("connect")] ConnectMcp,
    #[token("call")] CallTool,
    #[token("vessel", priority = 10)] Vessel,
    #[token("absorb", priority = 10)] Absorb,
    #[token("shield", priority = 10)] Shield,
    #[token("veil", priority = 10)] Veil,
    #[token("tier='bare_metal'")] TierBareMetal,
    #[token("tier='vram_only'")] TierVramOnly,
    #[token("temp")] Temp,
    #[token("bind")] Bind,
    #[token("quantize")] Quantize, 
    #[token(",")] Comma,
    #[token("(")] ParenOpen,
    #[token(")")] ParenClose,
    #[token("{")] BraceOpen,
    #[token("}")] BraceClose,
    #[token("worker")] Worker,
    #[token("share")] Share,
    #[token("hyper_quad")] HyperQuad,
    #[token("sys_exec")] SysExec,
    #[token("http_get")] HttpGet,
}