use crate::lexer::JutsuToken;
use crate::ast::{Program, Statement, Expression};
use logos::{Lexer, Logos};

// This module implements a Hand-Written Recursive Descent Parser.
// It takes a stream of tokens generated by the Logos Lexer and structures 
// them into an Abstract Syntax Tree (AST). The Evaluator will later 
// traverse this tree to execute the code.

/// The `Parser` struct maintains the state of the parsing process.
/// It holds the lexer iterator and a 1-token "lookahead" (`current_token`) 
/// to determine which grammar rule to apply next.
pub struct Parser<'a> {
    lexer: Lexer<'a, JutsuToken>,
    current_token: Option<JutsuToken>,
}

impl<'a> Parser<'a> {
    /// Initializes the parser, priming it with the very first token from the source code.
    pub fn new(source: &'a str) -> Self {
        let mut lexer = JutsuToken::lexer(source);
        let current_token = loop {
            match lexer.next() {
                Some(Ok(token)) => break Some(token),
                Some(Err(_)) => continue, // Silently skip lexical errors for now
                None => break None,
            }
        };
        Parser { lexer, current_token }
    }

    fn advance(&mut self) {
        self.current_token = loop {
            match self.lexer.next() {
                Some(Ok(token)) => break Some(token),
                Some(Err(_)) => continue,
                None => break None,
            }
        };
    }

    /// The main entry point. Parses the entire source code file into a `Program` AST node.
    pub fn parse(&mut self) -> Program {
        let mut statements = Vec::new();
        while self.current_token.is_some() {
            if let Some(stmt) = self.parse_statement() {
                statements.push(stmt);
            } else { 
                panic!("[Syntax Error] Unrecognized token or invalid syntax near: '{}'", self.lexer.slice());
            }
        }
        Program { statements }
    }

    /// Statement Router: Looks at the current token and delegates to the specific 
    /// parsing function for that statement type.
    fn parse_statement(&mut self) -> Option<Statement> {
        match self.current_token {
            Some(JutsuToken::Vessel) => self.parse_vessel_declaration(),
            Some(JutsuToken::Let) => self.parse_let_statement(),
            Some(JutsuToken::Print) => self.parse_print_statement(),
            Some(JutsuToken::Import) => self.parse_import_statement(),
            Some(JutsuToken::If) => self.parse_if_statement(),
            Some(JutsuToken::While) => self.parse_while_statement(),
            Some(JutsuToken::Def) => self.parse_function_declaration(), 
            Some(JutsuToken::Return) => self.parse_return_statement(),
            Some(JutsuToken::HexTrace) => self.parse_hextrace_block(),
            Some(JutsuToken::Backward) => self.parse_backward_statement(),
            Some(JutsuToken::Optim) => self.parse_optim_statement(),
            Some(JutsuToken::Reply) => self.parse_reply_statement(), 
            Some(JutsuToken::Identifier) => self.parse_identifier_driven_statement(),
            Some(JutsuToken::Shield) => self.parse_shield_block(),
            Some(JutsuToken::Veil) => self.parse_veil_block(),
            Some(JutsuToken::Worker) => self.parse_worker_block(),
            _ => {
                // If it doesn't start with let, if, while, etc., we try to read the entire line as an expression
                if let Some(expr) = self.parse_expression() {
                    Some(Statement::ExpressionStatement(expr))
                } else {
                    // If it is not a valid expression either, then it is indeed an unrecoverable syntax error
                    None
                }
            }
        }
    }

    /// Parses HTTP responses inside a veil block: `reply("HTTP OK")`
    fn parse_reply_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        let value = self.parse_expression()?;
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::ReplyStatement { value })
    }

    /// Parses the autograd backward pass trigger: `backward(tensor_name)`
    fn parse_backward_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        let target_var = if let Some(JutsuToken::Identifier) = self.current_token {
            let v = self.lexer.slice().to_string(); self.advance(); v
        } else { return None; };
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::BackwardStatement { target_var })
    }

    /// Parses the optimizer step: `optim(tensor_name, 0.01)`
    fn parse_optim_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        let target_var = if let Some(JutsuToken::Identifier) = self.current_token {
            let v = self.lexer.slice().to_string(); self.advance(); v
        } else { return None; };
        if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } else { return None; }
        let learning_rate = self.parse_expression()?;
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::OptimStatement { target_var, learning_rate })
    }

    /// Assigns a binding power (weight) to operators for correct mathematical precedence.
    fn get_precedence(token: &Option<JutsuToken>) -> u8 {
        match token {
            Some(JutsuToken::Or) => 1,
            Some(JutsuToken::And) => 2,
            Some(JutsuToken::EqualEqual) | Some(JutsuToken::NotEqual) => 3,
            Some(JutsuToken::LessThan) | Some(JutsuToken::GreaterThan) | 
            Some(JutsuToken::LessEqual) | Some(JutsuToken::GreaterEqual) => 4,
            Some(JutsuToken::Plus) | Some(JutsuToken::Minus) => 5, // Sum/Sub
            Some(JutsuToken::Star) | Some(JutsuToken::Slash) | Some(JutsuToken::Modulo) => 6, // Mult/Div/Mod
            _ => 0,
        }
    }

    /// Public wrapper for parsing expressions starting from the lowest precedence
    fn parse_expression(&mut self) -> Option<Expression> {
        self.parse_expression_with_precedence(0)
    }

    /// Core recursive expression parser using Pratt Parsing (Precedence Climbing)
    fn parse_expression_with_precedence(&mut self, precedence: u8) -> Option<Expression> {
        let mut left_expr = match self.current_token {
            // UNARY OPERATORS (-x, !x)
            Some(JutsuToken::Minus) | Some(JutsuToken::Bang) => {
                let operator = self.lexer.slice().to_string();
                self.advance();
                let right = self.parse_expression_with_precedence(7)?; // Prefix has very high precedence
                Some(Expression::PrefixOp { operator, right: Box::new(right) })
            }
            // PARENTHESES FOR MATHEMATICAL GROUPING
            Some(JutsuToken::ParenOpen) => {
                self.advance();
                let expr = self.parse_expression_with_precedence(0)?;
                if let Some(JutsuToken::ParenClose) = self.current_token {
                    self.advance();
                    Some(expr)
                } else {
                    None // Missing closing parenthesis
                }
            }
            Some(JutsuToken::Recv) => { 
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::RecvCall)
            }
            // Literal values
            Some(JutsuToken::True) => { self.advance(); Some(Expression::BooleanLiteral(true)) }
            Some(JutsuToken::False) => { self.advance(); Some(Expression::BooleanLiteral(false)) }
            Some(JutsuToken::Number) => { 
                let n = self.lexer.slice().parse::<f32>().unwrap_or(0.0);
                self.advance(); Some(Expression::NumberLiteral(n))
            }
            Some(JutsuToken::StringLiteral) => {
                let raw_str = self.lexer.slice().trim_matches('"');
                let s = raw_str.replace("\\n", "\n").replace("\\t", "\t").replace("\\\"", "\"");
                
                self.advance(); 
                Some(Expression::StringLiteral(s))
            }
            // THE 2D TENSOR PARSER
            Some(JutsuToken::Tensor) => { 
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                if let Some(JutsuToken::BracketOpen) = self.current_token { self.advance(); } else { return None; }
                
                let mut data = Vec::new();
                let shape;

                if let Some(JutsuToken::BracketOpen) = self.current_token {
                    let mut rows = 0;
                    let mut cols = 0;
                    
                    while self.current_token == Some(JutsuToken::BracketOpen) {
                        self.advance(); 
                        let mut current_cols = 0;
                        
                        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BracketClose) {
                            // Support full dynamic expressions instead of just raw numbers
                            if let Some(expr) = self.parse_expression() {
                                data.push(expr);
                                current_cols += 1;
                            }
                            if let Some(JutsuToken::Comma) = self.current_token { self.advance(); }
                        }
                        if rows == 0 { cols = current_cols; }
                        rows += 1;
                        if let Some(JutsuToken::BracketClose) = self.current_token { self.advance(); } 
                        if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } 
                    }
                    shape = vec![rows, cols];
                } else {
                    let mut cols = 0;
                    while self.current_token.is_some() && self.current_token != Some(JutsuToken::BracketClose) {
                        if let Some(expr) = self.parse_expression() {
                            data.push(expr);
                            cols += 1;
                        }
                        if let Some(JutsuToken::Comma) = self.current_token { self.advance(); }
                    }
                    shape = vec![cols];
                }

                if let Some(JutsuToken::BracketClose) = self.current_token { self.advance(); } 
                if let Some(JutsuToken::Comma) = self.current_token { self.advance(); }
                
                let mut requires_grad = false;
                if let Some(JutsuToken::Grad) = self.current_token {
                    self.advance();
                    if let Some(JutsuToken::Equal) = self.current_token { self.advance(); }
                    match self.current_token {
                        Some(JutsuToken::True) => { self.advance(); requires_grad = true; },
                        Some(JutsuToken::False) => { self.advance(); requires_grad = false; },
                        _ => {}
                    }
                }
                
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::TensorDeclaration { data, shape, requires_grad })
            }
            Some(JutsuToken::Infer) => {
                self.advance();
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                
                let model_name = if let Some(JutsuToken::Identifier) = self.current_token {
                    let m = self.lexer.slice().to_string(); self.advance(); m
                } else { return None; };

                if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } else { return None; }

                let prompt_var = if let Some(JutsuToken::Identifier) = self.current_token {
                    let p = self.lexer.slice().to_string(); self.advance(); p
                } else { return None; };

                let mut context_var = None;
                let mut grammar_var = None;

                if let Some(JutsuToken::Comma) = self.current_token {
                    self.advance();
                    if let Some(JutsuToken::Identifier) = self.current_token {
                        context_var = Some(self.lexer.slice().to_string());
                        self.advance();
                    }
                }
                
                if let Some(JutsuToken::Comma) = self.current_token {
                    self.advance();
                    if let Some(JutsuToken::Identifier) = self.current_token {
                        grammar_var = Some(self.lexer.slice().to_string());
                        self.advance();
                    }
                }

                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::InferCall { model_name, prompt_var, context_var, grammar_var })
            }
            Some(JutsuToken::Input) => {
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let prompt_expr = self.parse_expression()?; 
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::InputCall(Box::new(prompt_expr)))
            }
            Some(JutsuToken::ReadText) => {
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let filepath = if let Some(JutsuToken::StringLiteral) = self.current_token {
                    let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
                } else { return None; };
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::ReadTextCall(filepath))
            }
            Some(JutsuToken::Rag) => {
                self.advance();
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let query_var = if let Some(JutsuToken::Identifier) = self.current_token {
                    let v = self.lexer.slice().to_string(); self.advance(); v
                } else { return None; };
                if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } else { return None; }
                let doc_var = if let Some(JutsuToken::Identifier) = self.current_token {
                    let v = self.lexer.slice().to_string(); self.advance(); v
                } else { return None; };
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::RagCall { query_var, doc_var })
            }
            Some(JutsuToken::Share) => {
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let inner_expr = self.parse_expression()?; 
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::Share { value: Box::new(inner_expr) })
            }
            Some(JutsuToken::BracketOpen) => {
                self.advance();
                let mut elements = Vec::new();
                let mut first = true;
                while self.current_token.is_some() && self.current_token != Some(JutsuToken::BracketClose) {
                    if !first {
                        if let Some(JutsuToken::Comma) = self.current_token { self.advance(); }
                        else { panic!("[Syntax Error] Expected ',' in array near: '{}'", self.lexer.slice()); }
                    }
                    if let Some(expr) = self.parse_expression() { elements.push(expr); }
                    first = false;
                }
                if let Some(JutsuToken::BracketClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing ']' in array"); }
                Some(Expression::Array(elements))
            }
            Some(JutsuToken::BraceOpen) => {
                self.advance();
                let mut pairs = Vec::new();
                let mut first = true;
                while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
                    if !first {
                        if let Some(JutsuToken::Comma) = self.current_token { self.advance(); }
                        else { panic!("[Syntax Error] Expected ',' in dictionary"); }
                    }
                    let key = if let Some(JutsuToken::StringLiteral) = self.current_token {
                        self.lexer.slice().trim_matches('"').to_string()
                    } else if let Some(JutsuToken::Identifier) = self.current_token {
                        self.lexer.slice().to_string()
                    } else { panic!("[Syntax Error] Dictionary key must be a string or identifier"); };
                    self.advance();

                    if let Some(JutsuToken::Colon) = self.current_token { self.advance(); }
                    else { panic!("[Syntax Error] Expected ':' after dictionary key"); }

                    if let Some(val) = self.parse_expression() { pairs.push((key, val)); }
                    first = false;
                }
                if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing '}}' in dictionary"); }
                Some(Expression::Dictionary(pairs))
            }
            Some(JutsuToken::SysExec) => {
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let expr = self.parse_expression()?; // Supports variables, strings or concatenations
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::SysExecCall(Box::new(expr)))
            }
            Some(JutsuToken::HttpGet) => {
                self.advance(); 
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                let expr = self.parse_expression()?; // Support URL as expression
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Expression::HttpGetCall(Box::new(expr)))
            }
            Some(JutsuToken::Identifier) => {
                let id = self.lexer.slice().to_string();
                self.advance(); 
                
                if let Some(JutsuToken::Dot) = self.current_token {
                    self.advance(); 
                    if let Some(JutsuToken::Infer) = self.current_token {
                        self.advance(); 
                        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                        let prompt_var = if let Some(JutsuToken::Identifier) = self.current_token {
                            let v = self.lexer.slice().to_string(); self.advance(); v
                        } else { return None; };
                        
                        let mut context_var = None;
                        let mut grammar_var = None;
                        
                        // Try to read the second parameter (Context)
                        if let Some(JutsuToken::Comma) = self.current_token {
                            self.advance();
                            if let Some(JutsuToken::Identifier) = self.current_token {
                                context_var = Some(self.lexer.slice().to_string());
                                self.advance();
                            }
                        }

                        // Try to read the third parameter (GBNF Grammar)
                        if let Some(JutsuToken::Comma) = self.current_token {
                            self.advance();
                            if let Some(JutsuToken::Identifier) = self.current_token {
                                grammar_var = Some(self.lexer.slice().to_string());
                                self.advance();
                            }
                        }
                        
                        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                        
                        Some(Expression::InferCall { model_name: id, prompt_var, context_var, grammar_var })
                    } else {
                        // If there is a dot but it is not 'infer', we return the original ID
                        Some(Expression::Variable(id))
                    }
                } else if let Some(JutsuToken::ParenOpen) = self.current_token {
                    self.advance(); 
                    let mut args = Vec::new();
                    let mut first = true;
                    while self.current_token.is_some() && self.current_token != Some(JutsuToken::ParenClose) {
                        if !first {
                            if let Some(JutsuToken::Comma) = self.current_token { 
                                self.advance(); 
                            } else { 
                                panic!("[Syntax Error] Expected ',' between arguments near: '{}'", self.lexer.slice()); 
                            }
                        }
                        if let Some(expr) = self.parse_expression() { 
                            args.push(expr); 
                        } else { 
                            panic!("[Syntax Error] Invalid argument expression near: '{}'", self.lexer.slice()); 
                        }
                        first = false;
                    }
                    if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing ')' in function call"); }
                    
                    // Return the value to left_expr without aborting the function
                    Some(Expression::FunctionCall { name: id, args })
                } else if let Some(JutsuToken::BracketOpen) = self.current_token {
                    self.advance(); 
                    let index = self.parse_expression().expect("[Syntax Error] Expected index expression");
                    if let Some(JutsuToken::BracketClose) = self.current_token { 
                        self.advance(); 
                    } else { 
                        panic!("[Syntax Error] Missing ']' in index access near: '{}'", self.lexer.slice()); 
                    }
                    let left_expr = Expression::Variable(id.clone());
                    
                    Some(Expression::IndexAccess { left: Box::new(left_expr), index: Box::new(index) })
                } else {
                    // If it's not a method, function, or array, it's simply a variable
                    Some(Expression::Variable(id))
                }
            }
            _ => { return None; }
        }?;
        
        // INFIX LOOP (Precedence Climbing)
        while self.current_token.is_some() {
            let current_prec = Self::get_precedence(&self.current_token);
            if precedence >= current_prec { break; } // The next operator is weaker, resolve left_expr first

            match self.current_token {
                Some(JutsuToken::EqualEqual) | Some(JutsuToken::NotEqual) | 
                Some(JutsuToken::Star) | Some(JutsuToken::Plus) | Some(JutsuToken::Minus) | 
                Some(JutsuToken::Slash) | Some(JutsuToken::Modulo) |
                Some(JutsuToken::GreaterThan) | Some(JutsuToken::LessThan) | 
                Some(JutsuToken::GreaterEqual) | Some(JutsuToken::LessEqual) |
                Some(JutsuToken::And) | Some(JutsuToken::Or) => {
                    let operator = self.lexer.slice().to_string();
                    self.advance();
                    if let Some(right_expr) = self.parse_expression_with_precedence(current_prec) {
                        left_expr = Expression::InfixOp { left: Box::new(left_expr), operator, right: Box::new(right_expr) };
                    } else {
                        break;
                    }
                }
                _ => break,
            }
        }
        Some(left_expr)
    }

    fn parse_import_statement(&mut self) -> Option<Statement> {
        self.advance(); // Consume 'import'
        let path = if let Some(JutsuToken::StringLiteral) = self.current_token {
            let p = self.lexer.slice().trim_matches('"').to_string();
            self.advance();
            p
        } else {
            return None;
        };

        Some(Statement::ImportStatement { path })
    }

    fn parse_if_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        let condition = self.parse_expression()?;

        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Expected '{{' after if condition near: '{}'", self.lexer.slice()); }
        let mut consequence = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { consequence.push(stmt); } else { panic!("[Syntax Error] Invalid syntax inside if block near: '{}'", self.lexer.slice()); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing '}}' to close if block"); }

        let mut alternative = None;
        if let Some(JutsuToken::Else) = self.current_token {
            self.advance(); 
            
            if let Some(JutsuToken::If) = self.current_token {
                if let Some(else_if_stmt) = self.parse_if_statement() {
                    alternative = Some(vec![else_if_stmt]);
                }
            } else {
                if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Expected '{{' after else near: '{}'", self.lexer.slice()); }
                let mut alt_body = Vec::new();
                while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
                    if let Some(stmt) = self.parse_statement() { alt_body.push(stmt); } else { panic!("[Syntax Error] Invalid syntax inside else block near: '{}'", self.lexer.slice()); }
                }
                if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing '}}' to close else block"); }
                alternative = Some(alt_body);
            }
        }
        Some(Statement::IfStatement { condition, consequence, alternative })
    }

    fn parse_while_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        let condition = self.parse_expression()?;
        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { return None; }
        
        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { body.push(stmt); } else { self.advance(); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::WhileStatement { condition, body })
    }

    fn parse_hextrace_block(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { return None; }
        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { body.push(stmt); } else { self.advance(); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::HexTraceBlock { body })
    }

    fn parse_function_declaration(&mut self) -> Option<Statement> {
        self.advance(); 
        let name = if let Some(JutsuToken::Identifier) = self.current_token {
            let n = self.lexer.slice().to_string(); self.advance(); n
        } else { return None; };

        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        
        let mut params = Vec::new();
        let mut first = true;
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::ParenClose) {
            if !first {
                if let Some(JutsuToken::Comma) = self.current_token { 
                    self.advance(); 
                } else { 
                    panic!("[Syntax Error] Expected ',' between parameters near: '{}'", self.lexer.slice()); 
                }
            }
            if let Some(JutsuToken::Identifier) = self.current_token {
                params.push(self.lexer.slice().to_string());
                self.advance();
            } else {
                panic!("[Syntax Error] Expected parameter name near: '{}'", self.lexer.slice());
            }
            first = false;
        }
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing ')' in function declaration"); }

        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Expected '{{' to start function body"); }
        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { body.push(stmt); } else { panic!("[Syntax Error] Invalid syntax inside function body near: '{}'", self.lexer.slice()); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing '}}' to close function body"); }
        
        Some(Statement::FunctionDeclaration { name, params, body })
    }

    fn parse_return_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        let value = self.parse_expression()?;
        Some(Statement::ReturnStatement { value })
    }

    fn parse_let_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        let name = if let Some(JutsuToken::Identifier) = self.current_token {
            let n = self.lexer.slice().to_string(); self.advance(); n
        } else { return None; };

        if let Some(JutsuToken::Equal) = self.current_token { self.advance(); } else { return None; }
        let value = self.parse_expression()?;
        Some(Statement::LetStatement { name, value })
    }

    fn parse_print_statement(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        let expr = self.parse_expression()?;
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::PrintStatement { value: expr })
    }

    /// Can parse a re-assignment (x = 5) or an inference method call (x.infer)
    fn parse_identifier_driven_statement(&mut self) -> Option<Statement> {
        // Save the variable name and consume the identifier token
        let name = self.lexer.slice().to_string();
        self.advance(); 

        // Evaluate the following token and branch logic
        match self.current_token {
            Some(JutsuToken::Equal) => {
                // It's a pure assignment: x = 5
                self.advance(); // Consume the '='
                let value = self.parse_expression()?;
                Some(Statement::AssignmentStatement { name, value })
            }
            Some(JutsuToken::ParenOpen) => {
                self.advance(); // Consume the '('
                let mut args = Vec::new();
                let mut first = true;
                while self.current_token.is_some() && self.current_token != Some(JutsuToken::ParenClose) {
                    if !first {
                        if let Some(JutsuToken::Comma) = self.current_token { 
                            self.advance(); 
                        } else { 
                            panic!("[Syntax Error] Expected ',' between arguments near: '{}'", self.lexer.slice()); 
                        }
                    }
                    if let Some(expr) = self.parse_expression() { 
                        args.push(expr); 
                    } else { 
                        panic!("[Syntax Error] Invalid argument expression near: '{}'", self.lexer.slice()); 
                    }
                    first = false;
                }
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { panic!("[Syntax Error] Missing ')' in function call"); }
                
                let call_expr = Expression::FunctionCall { name: name.clone(), args };
                Some(Statement::LetStatement { name: "_".to_string(), value: call_expr })
            }
            Some(JutsuToken::Dot) => {
                // It's an object method: model.infer(...)
                self.advance(); // Consume the '.'
                if let Some(JutsuToken::Infer) = self.current_token { self.advance(); } else { return None; }
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }

                let prompt_var = if let Some(JutsuToken::Identifier) = self.current_token {
                    let var = self.lexer.slice().to_string(); self.advance(); var
                } else { return None; };

                let mut context_var = None;
                if let Some(JutsuToken::Comma) = self.current_token {
                    self.advance();
                    if let Some(JutsuToken::Identifier) = self.current_token {
                        context_var = Some(self.lexer.slice().to_string());
                        self.advance();
                    }
                }
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Statement::InferStatement { model_name: name, prompt_var, context_var })
            }
            _ => {
                // Invalid syntax (e.g., an isolated variable on a single line)
                None
            }
        }
    }

    fn parse_vessel_declaration(&mut self) -> Option<Statement> {
        self.advance(); 
        
        let name = if let Some(JutsuToken::Identifier) = self.current_token {
            let n = self.lexer.slice().to_string(); self.advance(); n
        } else { return None; };

        if let Some(JutsuToken::Equal) = self.current_token { self.advance(); } else { return None; }

        // Is it Absorb or HyperQuad?
        match self.current_token {
            Some(JutsuToken::Absorb) => {
                self.advance(); // Consume 'absorb'
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }

                let file_path = if let Some(JutsuToken::StringLiteral) = self.current_token {
                    let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
                } else { return None; };

                let mut tier = "bare_metal".to_string();
                let mut temp = 0.0; 
                let mut bind = 1.0; 
                let mut quantize = false; 

                // We read the extra parameters of the absorb
                while let Some(JutsuToken::Comma) = self.current_token {
                    self.advance();
                    match self.current_token {
                        Some(JutsuToken::TierBareMetal) => { tier = "bare_metal".to_string(); self.advance(); },
                        Some(JutsuToken::TierVramOnly) => { tier = "vram_only".to_string(); self.advance(); },
                        Some(JutsuToken::Temp) => {
                            self.advance(); 
                            if let Some(JutsuToken::Equal) = self.current_token { self.advance(); }
                            if let Some(JutsuToken::Number) = self.current_token {
                                temp = self.lexer.slice().parse::<f32>().unwrap_or(0.0); self.advance();
                            }
                        },
                        Some(JutsuToken::Bind) => {
                            self.advance(); 
                            if let Some(JutsuToken::Equal) = self.current_token { self.advance(); }
                            if let Some(JutsuToken::Number) = self.current_token {
                                bind = self.lexer.slice().parse::<f32>().unwrap_or(1.0); self.advance();
                            }
                        },
                        Some(JutsuToken::Quantize) => {
                            self.advance(); 
                            if let Some(JutsuToken::Equal) = self.current_token { self.advance(); }
                            if let Some(JutsuToken::True) = self.current_token {
                                quantize = true; self.advance();
                            } else if let Some(JutsuToken::False) = self.current_token {
                                quantize = false; self.advance();
                            }
                        },
                        _ => break,
                    }
                }
                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
                Some(Statement::VesselDeclaration { name, file_path, tier, temp, bind, quantize })
            },
            
            Some(JutsuToken::HyperQuad) => {
                self.advance(); // Consume 'HyperQuad'
                if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
                
                // We extract the original file to be compressed
                let model_ident = if let Some(JutsuToken::StringLiteral) = self.current_token {
                    let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
                } else { return None; };

                if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } else { return None; }
                
                // We extract the destination file name
                let target = if let Some(JutsuToken::StringLiteral) = self.current_token {
                    let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
                } else { return None; };

                if let Some(JutsuToken::Comma) = self.current_token { self.advance(); } else { return None; }

                // The same applies to the compression type ("Q4_K_M")
                let compression = if let Some(JutsuToken::StringLiteral) = self.current_token {
                    let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
                } else { return None; };

                if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }

                Some(Statement::HyperQuadDirective { name, model_ident, target, compression })
            },
            
            _ => None // If it's not absorb or HyperQuad after the '=', it's a syntax error
        }
    }

    fn parse_shield_block(&mut self) -> Option<Statement> {
        self.advance();
        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::Identifier) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::Equal) = self.current_token { self.advance(); } else { return None; }
        let max_vram = if let Some(JutsuToken::StringLiteral) = self.current_token {
            let s = self.lexer.slice().trim_matches('"').to_string(); self.advance(); s
        } else { return None; };
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { return None; }

        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { body.push(stmt); } else { self.advance(); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::ShieldBlock { max_vram, body })
    }

    fn parse_veil_block(&mut self) -> Option<Statement> {
        self.advance();
        let mut name = "backend_server".to_string(); 

        if let Some(JutsuToken::Identifier) = self.current_token {
            name = self.lexer.slice().to_string();
            self.advance();
        }

        if let Some(JutsuToken::ParenOpen) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::Identifier) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::Equal) = self.current_token { self.advance(); } else { return None; }
        
        let port = self.parse_expression()?; 
        
        if let Some(JutsuToken::ParenClose) = self.current_token { self.advance(); } else { return None; }
        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { return None; }

        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { body.push(stmt); } else { self.advance(); }
        }
        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { return None; }
        Some(Statement::VeilBlock { name, port, body })
    }

    fn parse_worker_block(&mut self) -> Option<Statement> {
        self.advance(); 
        if let Some(JutsuToken::BraceOpen) = self.current_token { self.advance(); } else { return None; }

        let mut body = Vec::new();
        while self.current_token.is_some() && self.current_token != Some(JutsuToken::BraceClose) {
            if let Some(stmt) = self.parse_statement() { 
                body.push(stmt); 
            } else { 
                self.advance(); 
            }
        }

        if let Some(JutsuToken::BraceClose) = self.current_token { self.advance(); } else { return None; }
        
        Some(Statement::WorkerBlock { body })
    }
}

/// Unit Tests

#[cfg(test)] // This directive tells Rust: "Only compile this if you run 'cargo test'"
mod tests {
    use super::*;
    use crate::ast::{Expression, Statement};

    #[test]
    fn test_parse_let_statement() {
        let input = "let dog = 100";
        let mut parser = Parser::new(input);
        
        let program = parser.parse();

        assert_eq!(program.statements.len(), 1, "There should be exactly 1 instruction");

        // We perform pattern matching to ensure the AST was formed correctly
        match &program.statements[0] {
            Statement::LetStatement { name, value } => {
                assert_eq!(name, "dog", "The variable name should be 'dog'");
                
                match value {
                    Expression::NumberLiteral(val) => assert_eq!(*val, 100.0, "The value should be 100"),
                    _ => panic!("The value was not parsed as a literal number"),
                }
            }
            _ => panic!("The instruction was not recognized as a LetStatement"),
        }
    }

    #[test]
    fn test_syntax_error_input() {
        // Tested that the parser would fail and panic if we misspelled the syntax
        let input = "input("; // The parenthesis needs to be closed
        
        // The catch_unwind tag catches the expected panic (optional, but useful)
        let result = std::panic::catch_unwind(|| {
            let mut parser = Parser::new(input);
            parser.parse();
        });
        
        assert!(result.is_err(), "The parser should have triggered a panic due to a syntax error.");
    }
}